spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
